[package]
name = "lexi-graphql-server"
version = "0.1.0"
edition = "2021"


[dependencies]
actix-web = "4"
juniper = "0.15.11"
juniper_actix = "0.4.0"
tokio = { version = "1.32.0", features = ["full"] }
tonic = "0.9.2"
prost = "0.11.9"
